name: Deploy JupyterLite site

on:
  push:
    branches: [ main ]   # change to 'master' if needed
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install JupyterLite
        run: |
          pip install jupyterlite jupyterlab

      - name: Build JupyterLite site
        run: |
          jupyter lite build --contents content/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_output
